# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='product_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='product',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
