# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('engagement_rate', models.DecimalField(decimal_places=20, max_digits=20)),
                ('followers', models.TextField()),
                ('followings', models.TextField()),
                ('num_posts', models.IntegerField()),
                ('num_likes', models.IntegerField()),
                ('num_commenters', models.IntegerField()),
                ('num_views', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
