# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='num_followers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='num_followings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='influencer',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=20, max_digits=22),
        ),
    ]
