# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('full_name', models.TextField(null=True)),
                ('user_pk', models.IntegerField()),
                ('is_verified', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('follow_status', models.CharField(max_length=5)),
                ('object_pk', models.IntegerField()),
                ('is_favorite', models.BooleanField()),
            ],
        ),
    ]
