# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20171009_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='follow',
            name='object_pk',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user_pk',
            field=models.BigIntegerField(),
        ),
    ]
