# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20170917_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=20, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followings',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='num_commenters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='num_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='num_followings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='num_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='num_posts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='num_views',
            field=models.IntegerField(null=True),
        ),
    ]
