# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('usertags_count', models.IntegerField(null=True)),
                ('media_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('is_business', models.BooleanField()),
                ('has_chaining', models.BooleanField()),
                ('geo_media_count', models.IntegerField(null=True)),
                ('full_name', models.TextField(null=True)),
                ('user_pk', models.IntegerField()),
                ('is_verified', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('is_favorite', models.BooleanField()),
                ('external_url', models.TextField(null=True)),
            ],
        ),
    ]
