# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20171010_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pk',
            field=models.BigIntegerField(),
        ),
    ]
