# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20171010_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag_Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.BigIntegerField()),
                ('hashtag', models.TextField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
