# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_hashtag_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag_dictionary',
            name='code_list',
            field=models.TextField(null=True),
        ),
    ]
