# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_hashtag_dictionary_code_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag_dictionary',
            name='hashtag',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
