# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_auto_20171024_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower_count',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
