# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_auto_20171103_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=20, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_commenters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
