# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_auto_20171114_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_follower_commenters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_follower_likes',
            field=models.IntegerField(null=True),
        ),
    ]
