# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_auto_20171121_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_DM_sent',
            field=models.IntegerField(null=True),
        ),
    ]
