# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_user_count_dm_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
