# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0021_auto_20171127_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campaign_kind',
            field=models.TextField(null=True),
        ),
    ]
