# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0022_user_campaign_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.BigIntegerField(db_index=True)),
                ('brandname', models.CharField(db_index=True, max_length=200)),
                ('page_rank', models.DecimalField(decimal_places=20, max_digits=22, null=True)),
                ('graph_type', models.CharField(db_index=True, max_length=5)),
            ],
        ),
    ]
