# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0023_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
